// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teste_Stage.Data;

#nullable disable

namespace Teste_Stage.Migrations;

[DbContext(typeof(EntrevistaContext))]
partial class EntrevistaContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("Teste_Stage.Models.Candidato", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Endereco")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("NumeroContato")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("Candidato");
            });

        modelBuilder.Entity("Teste_Stage.Models.Entrevista", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("CandidatoId")
                    .HasColumnType("int");

                b.Property<string>("Cargo")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("FitCultral")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<int>("Idade")
                    .HasColumnType("int");

                b.Property<float>("PontuacaoTest")
                    .HasColumnType("float");

                b.Property<bool>("TesteFeito")
                    .HasColumnType("tinyint(1)");

                b.HasKey("Id");

                b.HasIndex("CandidatoId");

                b.ToTable("Entrevistas");
            });

        modelBuilder.Entity("Teste_Stage.Models.Entrevista", b =>
            {
                b.HasOne("Teste_Stage.Models.Candidato", "Candidato")
                    .WithMany()
                    .HasForeignKey("CandidatoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Candidato");
            });
#pragma warning restore 612, 618
    }
}
